# Generated by Django 3.2.3 on 2021-06-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
