# Generated by Django 3.2.3 on 2021-06-14 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0009_payment_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_ids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment_ids',
            name='ids',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
